mysite/myapp/urls.py
from django.urls import path
from myapp.views import index,indexItem

app_name = "myapp"

urlpatterns = [
    #http://127.0.0.1:8000/myapp/
    path('',index),
    path('<int:my_id>/',indexItem, name="detail"),
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    #http://127.0.0.1:8000/myapp/
    path("myapp/", include("myapp.urls", namespace="myapp"))
]

mysite/myapp/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length = 200)

    def __str__(self) -> str:
        return self.name

mysite/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product

# Create your views here.

def index(request):
    items = Product.objects.all()
    context = {
        'items': items
    }
    return render(request, "myapp/index.html", context)

def indexItem(request, my_id):
    item = Product.objects.get(id=my_id)
    context = {
        'item': item
    }
    return render(request, "myapp/detail.html", context=context)

def contacts(request):
    return render(request, "myapp/contacts.html")

mysite/myapp/templates/myapp/detail.html
<html>
<head>
</head>
<body>
    <h1>This is detail page : {{item.name}}</h1>
</body>
</html>

mysite/myapp/templates/myapp/index.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    </head>
    <body class="bg-sky-600">
        <h1>This is index template</h1>
        <h2>
            <!-- <a href="/myapp/hello/{{item.id}}/"></a> -->
            {% for item in items %}
            <a href="{% url 'myapp:detail' item.id %}">
            ID: {{item.id}} | Имя: {{item.name}} | Цена: {{item.price}} | Описание:{{item.description}} <br/>
            </a>
            {% endfor %}
        </h2>
    </body>
</html>